#!/bin/bash
# homebridge-rpi/opt/pigpio/cgi/vcgencmd
# Copyright © 2019 Erik Baauw.  All rights reserved.
#
# Homebridge plugin for Raspberry Pi.

umask 022
exec 2> /opt/pigpio/vcgencmd.err
exec > /opt/pigpio/vcgencmd.out

echo -n "{"
echo -n "\"date\":\"$(date -uIseconds)\","
echo -n "\"load\":$(uptime | sed -e "s/.*load average: \([^ ]*\),.*/\1/"),"
echo -n "\"temp\":$(vcgencmd measure_temp | sed -e "s/temp=\(.*\)'C/\1/"),"
echo -n "\"freq\":$(vcgencmd measure_clock arm | cut -f 2 -d =),"
echo -n "\"volt\":$(vcgencmd measure_volts | sed -e "s/volt=\(.*\)V/\1/"),"
echo -n "\"throttled\":\"$(vcgencmd get_throttled | cut -f 2 -d =)\""
echo -n "}"
